version : "3.11"
services:
  postgres:
    image: postgres:16-alpine
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: bot_test
      POSTGRES_USER: kirill
      POSTGRES_DB: busy_beaver
    ports:
      - "5432:5432" 
    expose:
      - "5432"
    volumes:
      - postgres-data:${POSTGRES_DATA}
    networks:
      - postgres
  bot:
    image: skkiba/telegram_bot
    restart: always
    env_file:
      - .env
    depends_on:
      - postgres
    command: python -m bot
    networks:
      - postgres

    
volumes:
  postgres-data:

networks:
  postgres:
    driver: bridge


